### ISSUE TITLE
Creaste login panel on front

### ISSUE THREAD

**Issue by MathMatowicki** [MathMatowicki/HouseAR#8]
Create the login component. It should be available to login by standard login and password or by google/microsoft accounts

**Comment by alanbosco003** [comment]
Is it just to create a login UI or do you want to integrate the API as well?

**Comment by MathMatowicki** [comment]
First you can do only the front-end component without API integration. This issue is labeled by front so its only on fron side issue.

**Comment by Vishnudas2003** [comment]
Hi there!

I would like to take on this task. I find the implementation of the login component interesting and would be happy to contribute to it. I'll start working on it and keep the team updated on my progress.

Cheers!
Vishnu Das Puthukudi

**Comment by Vishnudas2003** [comment]
I have created the front-end-component 
![image](https://github.com/MathMatowicki/HouseAR/assets/94338168/a67539ed-db05-494e-9cee-4e6c81513d69)

Do you want me to integrate with API ?

**Comment by MathMatowicki** [comment]
Can you create a pull request for this code? I'll make another issue for you on the backend.

**Comment by Vishnudas2003** [comment]
Created a pull request
